FROM logstash:latest

RUN mkdir -p /etc/logstash/conf.d/
COPY config/logstash.conf /etc/logstash/conf.d/

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json 
